# Questa è una prova di pull condizionato ad una chiave utente e una push condizionata al controllo dei test

name: Android CI Testing prima di push
on: 
  push:
    branches: [ master, main ]
  pull_request: 
    branches:  [ master, main ]
jobs: 
  build: 
    runs-on: macOS-latest
    permissions:
           checks: write
           contents: read
           issues: read
           pull-requests: write
    strategy:
      matrix:
        java_version: [11]
        api-level: [29]
        arch: [x86]
        
    steps:
    
      - name: Install coreutils for macOS
        run: brew install coreutils
        
      - uses: malinskiy/action-android/install-sdk@release/0.0.8  
        
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
        # fromJSON() converts a string into a JSON object or value
        # ${{ toJSON('{"FAVORITE_FRUIT" : "APPLE", "FAVORITE_COLOR" : "BLUE"}') }}
      #- name: From JSON
        #env: ${{ toJSON('{"FAVORITE_FRUIT": "APPLE", "FAVORITE_COLOR": "BLUE"}') }}
        #run: echo "I would like a ${FAVORITE_COLOR} ${FAVORITE_FRUIT}"
        
      - name: Controlla se il file esiste e esegui una serie di istruzioni
        run: |
         FILE=Example.json
         if [ -f "$FILE" ]; then echo "$FILE exists."
         else echo "$FILE does not exist."
         fi
         FILE2=Exampl.json
         if [ -f "$FILE" ]; then echo "$FILE exists."
         else echo "$FILE does not exist."
         fi
         test -f /etc/resolv.conf && echo "$FILE exists."
         test -f Exampl.json && echo "$FILE exists."
         test -f ./Example.json && echo "$FILE exists."
        
        #verifica la versione di bash - Ci vuole autorizzazione per cambiare versione di Bash Shell
        #chsh -s /usr/local/bin/bash
        #Si scarica e usa JQ per leggere Json in Bash
        #brew install jq   e si usa per leggere alcuni nodi di JSON!!!!
        #che io sappia non si puo' mettere il commento intralinea!! e la pipeline input e output sono collegati!!
        # echo `::set-output name=elmira::$value`
        #Crea un file Json (invece di reindirizzarlo) e lo assegna ad una variabile!!!!!
      - name: check bash
        id: prova
        run: |
          echo 'Job context is ${{ toJSON(job) }}'
          ls
          echo "$PATH"
          bash --version
          brew install jq
          STR="Hello World!"
          echo $STR 
          value=`cat Example.json`
          echo $value
          echo "$value"
          echo document=GIALLLO >> $GITHUB_ENV
          echo scritto=eccomi qua $value >> $GITHUB_ENV
          
          
      # echo " il valore del primo ${{steps.prova.outputs.elmira }}"
      - name: Testa Outputs
        run: |
          echo "Il valore della variabile e' il seguente  ${{env.document}}"
          echo "e il valore della variabile complessa ${{env.scritto}}"
      
      - name: Check Gradle checksum
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ZacSweers/check-gradle-checksums/master/check-gradle-checksums.sh)"
        
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          #java-distribution: temurin
          java-version: ${{ matrix.java_version }}
          
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2
          
      # Necessario oppure già compreso?
      #- name: Install Android SDK
      #  uses: malinskiy/action-android/install-sdk@release/0.0.3
       
      # Forse è questo il problema!!!! forse vanno aumentati i diritti e quindi semplicemente scompare messaggio di non poter portare
      
      #ORIGINARIAMENTE SOLO +x
      - name: Change wrapper permissions
        run: chmod +rwx ./gradlew
        
      # Forse e' un doppione di quello sopra
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      
      # Fa la build con sistema nuovo
      #- name: build nuovo sistema
        #uses: gradle/gradle-build-action@v2
        #with:
          #arguments: build  
        
      - name: Configure Gradle
        # Initial gradle configuration, install dependencies, etc..
        run: ./gradlew help  
        
       #Stampa per verificarne la correttezza e utili nel caso di problemi
      - name: echo-default-env-variables
        run: |
            echo "Home: ${HOME}"
            echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
            echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
            echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
            echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
            echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
            echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
            echo "GITHUB_SHA: ${GITHUB_SHA}"
            echo "GITHUB_REF: ${GITHUB_REF}"
            echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
    
      - name: Update latest version in realtime database
        uses: w9jds/firebase-trigger@master
        #env:
          #GITHUB_CONTEXT: ${{ toJSON(github.repository) }}
          #NOME_REPOSITORY: 
        with:
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
          databaseUrl: https://databasericette-beeb7.firebaseio.com
          path: "${{ github.repository }}"
          #Si devono mettere come segreto!!!
          value: "${{ github.repository }}"
          
      # echo 'GITHUB_JSON=${(cat ./Example.json)}' >> $GITHUB_ENV
      - name: Set env
        run: |
          cat ./Example.json
          echo "GITHUB_BEPPE='eccomi'" >> $GITHUB_ENV
          echo 'GITHUB_GIUSEPPE="giuseppe"' >> $GITHUB_ENV
          JSON=$(cat ./Example.json)
          echo GITHUB_JSON=$(Example.json) >> $GITHUB_ENV
        #echo 'Job context is ${{ toJSON(job) }}'
        
      - name: Testa variabili ambientali
        run: |
          echo $GITHUB_BEPPE
          echo " $GITHUB_BEPPE"
          echo " $GITHUB_GIUSEPPE"
          echo " ${GITHUB_BEPPE}"
          echo " ${{env.GITHUB_JSON}}"
        # echo " ${{GITHUB_BEPPE}}"
          
      # Leggi il file Json a video e immagazzina il contenuto in una variabile
      #commenti: # echo "valori: ${cat Example.Json}"
      # the following lines are only required for multi line json
      # content="${content//'%'/'%25'}"
      # content="${content//$'\n'/'%0A'}"
      # content="${content//$'\r'/'%0D'}"
      #- name: Read and Store JSON file ( for debug )
        #id: readJsonXFire
        #run: |
          #ls app
          #ls ./
          #ls
          #cat ./Example.Json
          #echo '***************************************linea di separazione*********************************************'
          #content="$(cat Example.Json)"
          #oggetto="${Example.Json}"
          #echo '***************************************linea di separazione*********************************************'
          #content="${content//'%'/'%25'}"
          #content="${content//$'\n'/'%0A'}"
          #content="${content//$'\r'/'%0D'}"
          #parola="antonio"
        #echo 'verifica che la parola associata alla variabile parola un nome proprio: $parola'
        #echo 'oppure $parola oppure ${parola}'
        #echo '::set-output name=documento::$(content)'
        #echo '::set-output name=beppe::"eccomi"'
        #echo '::set-output name=elmira::$parola'
          
      # e poi lo va a leggere!!!! verificato che lo passa 
      # echo "${{fromJson(steps.readJSON2Firebase.outputs.packageJson).version}}"
      # echo "$(fromJson(steps.readJSON2Firebase.outputs.packageJson).version)"
      # stringa = "${{steps.readJSON2Firebase.outputs.packageJson}}"
      #- name: Testa Json 
        #run: |
          #echo " il valore del primo ${{steps.readJsonXFire.outputs.documento }}"
          #echo " il valore del secondo ${{steps.readJsonXFire.outputs.beppe}}"
          #echo ' il valore del terzo: ${{steps.readJsonXFire.outputs.beppe}}'
          #echo "il valore del quarto:  ${{steps.readJsonXFire.outputs.elmira}}"
          
      # salvataggio del file json convertito in precedenza
      - name: Update latest version in realtime database
        uses: w9jds/firebase-trigger@master
        id: readJSON
        with:
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
          databaseUrl: https://databasericette-beeb7.firebaseio.com
          databaseType: firestore
          path: "${{ github.repository }}"
          #Si devono mettere come segreto!!!
          #value: ${{ fromJSON(example.json)}}
          #per firestore si deve inserire un file!!!!!!!
          #value: "$(fromJson(steps.readJson.outputs.packageJson).version)"
          value: scp Example.json
     
     # Prova a lanciare task locale che visualizza la directory dei risultati dei test 
      #- name: lancia task locale
        #run: ./gradlew showDirs
     
     # Si può usare assemble invece di build (che è assemble + check)
      - name: Build Project
        run: ./gradlew assemble --stacktrace
        
         # Fa la build con sistema nuovo
      #- name: Instrumented check
        #uses: gradle/gradle-build-action@v2
        #with:
          #arguments: connectedCheck
      
      #vecchio test
      - name: Run Instrumentation Tests (reactivecircus)
        uses: reactivecircus/android-emulator-runner@v2.6.1
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          target: default
          #arch: x86
          profile: Nexus 6
          script: |
            ./gradlew connectedCheck 
            ./gradlew connectedAndroidTest
            ls app/build/outputs/androidTest-results/connected
            ls app/build/outputs/apk/androidTest
            ls app/build/outputs/apk/debug
            ls app/build/outputs/apk/release
            adb install app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
            adb install app/build/outputs/apk/debug/app-debug.apk
            adb shell pm list instrumentation
            adb shell am instrument -w -e class com.example.verifica.ExampleInstrumentedTest com.example.verifica.test/androidx.test.runner.AndroidJUnitRunner
            adb shell ls sdcard/Android/data/com.example.verifica/files
            adb shell cat sdcard/Android/data/com.example.verifica/files/giuseppe.txt
            adb pull sdcard/Android/data/com.example.verifica/files/giuseppe.txt app
            ls 
            ls app
            ./gradlew leggiReport
          #adb devices
          #adb shell ls sdcard/Android/data
          #script: ./gradlew connectedCheck --stacktrace
          #script: adb shell am instrument -w -e class com.example.tests_vari.ExampleInstrumentedTest  com.example.tests_vari.test/androidx.test.runner.AndroidJUnitRunner --rerun-tasks
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          
      #vecchio vecchio test strumentale (nella versione iniziale era stato tolto )
      #- name: Run Instrumentation Tests
       # uses: vgaidarji/android-github-actions-emulator@v1.0.1
        #with:
          #cmd: ./gradlew connectedCheck --stacktrace
          #api: 30
          #tag: default
          #abi: x86

      - name: Reclaim Memory
        run: ./gradlew --stop && jps|grep -E 'KotlinCompileDaemon|GradleDaemon'| awk '{print $1}'| xargs kill -9
        
        #Adesso si fanno i check che abbiamo omesso in assemble - Vedi articolo per differenza tra check e test!!!!! check e' per test composti
      #- name: Final Checks
        #run: ./gradlew check --stacktrace
        
      #- name: Upload APK
        #uses: actions/upload-artifact@v2.2.4
        #with:
          #name: apk
          #path: app/build/outputs/apk/debug/app-debug.apk
